### ISSUE TITLE
Errors while building the project

### ISSUE THREAD

**Issue by sohaib-l** [adujardin/zed-openpose#1]
Hello,

Thank you for this interesting project!

I was trying to build it (it took me a lot of time to install openpose ^^) and I had some issues. Here's the log:

[100%] Linking CXX executable zed_openpose
/usr/bin/ld: warning: libhidapi-libusb.so.0, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpng12.so.0, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libturbojpeg.so.0, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libusb-0.1.so.4, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnppc.so.9.0, needed by //usr/local/cuda-9.0/lib64/libnppial.so.9.0, may conflict with libnppc.so.8.0
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_get_IHDR@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_tRNS@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_palette_to_rgb@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_write_image@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_open_path'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_write'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_read_fn@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_close'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_free_enumeration'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_bgr@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjInitCompress@TURBOJPEG_1.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjFree@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_image@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_write_info@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_find_devices'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_channels@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_sig_cmp@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_packing@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_destroy_write_struct@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_strip_alpha@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_destroy_read_struct@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_read'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_rgb_to_gray@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_exit'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_image_height@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjCompress2@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_rows@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_create_write_struct@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_color_type@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_write_end@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_compression_level@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjDecompress2@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_update_info@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_write_fn@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_filter@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_strip_16@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_create_info_struct@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjAlloc@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_init_io@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_find_busses'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_swap@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_tRNS_to_alpha@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_valid@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_interlace_handling@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_write_png@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjDestroy@TURBOJPEG_1.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_end@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_compression_strategy@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_enumerate'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_get_io_ptr@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_expand_gray_1_2_4_to_8@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_init'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_bit_depth@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_busses'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_create_read_struct@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_error@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_sig_bytes@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_gray_to_rgb@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_image_width@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjInitDecompress@TURBOJPEG_1.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_IHDR@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_info@PNG12_0'
collect2: error: ld returned 1 exit status
CMakeFiles/zed_openpose.dir/build.make:140: recipe for target 'zed_openpose' failed
make[2]: *** [zed_openpose] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/zed_openpose.dir/all' failed
make[1]: *** [CMakeFiles/zed_openpose.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can you please tell me where the error is coming from?

**Comment by adujardin** [comment]
Hi,
My guess is that the ZED SDK dependencies were not installed correctly. Did you select 'yes' when asking to install them during the ZED SDK installation?
Also, it seems you have installed Cuda 8 on your machine but the ZED SDK you installed is asking for Cuda 9, it only supports the exact Cuda version.

FYI, it's kinda tricky work with a ZED SDK compatible with Cuda 8 (<=2.2.0) with Ubuntu 1604 and a recent kernel, see https://github.com/stereolabs/zed-ros-wrapper/issues/178

**Comment by adujardin** [comment]
The 2.2.0 is labeled "Cuda 8", here's the link: https://download.stereolabs.com/zedsdk/2.2/ubuntu_cuda8

**Comment by sohaib-l** [comment]
I have uninstalled cuda 9.0, and installed the Zed SDk version you gave me. However, when installing the Zed SDK I have got:

ERROR : Found CUDA 8.0 but the ZED SDK requires 9.0
The ZED will NOT work with this CUDA version (8.0), Continue  [Y/n] ?

I continued anyway but I ended up getting +- the same errors.

[100%] Linking CXX executable zed_openpose
/usr/bin/ld: warning: libhidapi-libusb.so.0, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpng12.so.0, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libturbojpeg.so.0, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libusb-0.1.so.4, needed by /usr/local/zed/lib/libsl_input.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcudart.so.9.0, needed by /usr/local/zed/lib/libsl_core.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnppial.so.9.0, needed by /usr/local/zed/lib/libsl_core.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnppisu.so.9.0, needed by /usr/local/zed/lib/libsl_core.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnppidei.so.9.0, needed by /usr/local/zed/lib/libsl_core.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnppif.so.9.0, needed by /usr/local/zed/lib/libsl_core.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnppist.so.9.0, needed by /usr/local/zed/lib/libsl_zed.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnpps.so.9.0, needed by /usr/local/zed/lib/libsl_zed.so, not found (try using -rpath or -rpath-link)
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_get_IHDR@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_tRNS@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_palette_to_rgb@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaCreateChannelDesc@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_write_image@PNG12_0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppiFilterBoxBorder_8u_C1R@libnppif.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_open_path'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaEventCreateWithFlags@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaStreamSynchronize@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_write'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaGetErrorString@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaMemcpyAsync@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaGetDevice@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `nppiMalloc_32f_C1@libnppisu.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaRuntimeGetVersion@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_read_fn@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaHostAlloc@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_close'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppiHistogramRangeGetBufferSize_32f_C1R@libnppist.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaGetDeviceProperties@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `nppiFree@libnppisu.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_free_enumeration'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_bgr@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjInitCompress@TURBOJPEG_1.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjFree@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_image@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `__cudaRegisterFunction@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaSetupArgument@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMemset2DAsync@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMemcpyToSymbol@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_write_info@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMemcpy2D@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_find_devices'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_channels@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaLaunch@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_sig_cmp@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_packing@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMemcpy2DAsync@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaStreamCreate@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `nppiSet_32f_C1R@libnppidei.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_destroy_write_struct@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_strip_alpha@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `__cudaRegisterTexture@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_destroy_read_struct@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `nppiMalloc_8u_C1@libnppisu.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_read'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaFreeHost@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_rgb_to_gray@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_exit'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_image_height@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjCompress2@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMemcpyToSymbolAsync@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_rows@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMemcpy@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_create_write_struct@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_color_type@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_write_end@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMallocManaged@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_compression_level@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `nppiFilterBoxBorder_8u_C4R@libnppif.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `__cudaUnregisterFatBinary@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `__cudaRegisterVar@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaFree@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjDecompress2@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_core.so: undefined reference to `nppiAdd_32f_C1R@libnppial.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_update_info@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_write_fn@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_filter@PNG12_0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppsMalloc_8u@libnpps.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_strip_16@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMallocPitch@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaMalloc3D@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaEventRecord@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppiMulC_32f_C1IR@libnppial.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_create_info_struct@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjAlloc@TURBOJPEG_1.2'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaBindTexture2D@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppsMalloc_32s@libnpps.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaDeviceSynchronize@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppsFree@libnpps.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaMemGetInfo@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_init_io@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_find_busses'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_swap@PNG12_0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaSetDevice@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_tRNS_to_alpha@PNG12_0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppiHistogramRange_32f_C1R@libnppist.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaMemset3D@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaConfigureCall@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_valid@PNG12_0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaDeviceReset@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_interlace_handling@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_write_png@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `__cudaRegisterFatBinary@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjDestroy@TURBOJPEG_1.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMalloc@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_end@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_compression_strategy@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaGetLastError@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `hid_enumerate'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_get_io_ptr@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_expand_gray_1_2_4_to_8@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_init'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaDriverGetVersion@libcudart.so.9.0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `nppsMalloc_32f@libnpps.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_bit_depth@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaGetDeviceCount@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `usb_busses'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaStreamDestroy@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_create_read_struct@PNG12_0'
/usr/local/zed/lib/libsl_zed.so: undefined reference to `cudaStreamAddCallback@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_error@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaMemset2D@libcudart.so.9.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_sig_bytes@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_set_gray_to_rgb@PNG12_0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `png_get_image_width@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `tjInitDecompress@TURBOJPEG_1.0'
/usr/local/zed/lib/libsl_core.so: undefined reference to `cudaUnbindTexture@libcudart.so.9.0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_set_IHDR@PNG12_0'
/usr/local/zed/lib/libsl_input.so: undefined reference to `png_read_info@PNG12_0'
collect2: error: ld returned 1 exit status
CMakeFiles/zed_openpose.dir/build.make:140: recipe for target 'zed_openpose' failed
make[2]: *** [zed_openpose] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/zed_openpose.dir/all' failed
make[1]: *** [CMakeFiles/zed_openpose.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sohaib-l** [comment]
Hi @adujardin,

I have succeeded to build the project (CUDA8 + ZED SDK 2.2.0). However, when I tried to run the project, I had the error: CAMERA NOT DETECTED. I tried using 3 different cameras but with no success.
I have: 
- UBUNTU 17.10
- GeForce GTX 1080 Ti/PCIe/SSE2

**Comment by adujardin** [comment]
What's your kernel version?  (`uname -r` to check)
As I said, ZED SDK 2.2.0 won't work on recent Linux kernel (>4.4) and I suspect Ubuntu 17.10 is at least at 4.13 by default.
See this related issue: https://github.com/stereolabs/zed-examples/issues/34

**Comment by sohaib-l** [comment]
Thank you for your answer.
I have got 4.13.0-43-generic (as you expected).

I see now. I'll try to either build OpenPose with CUDA9 or Install UBUNTU 16.04.

Thank you again
